name: CI
run-name: ${{ github.actor }} created a pull request

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build project
        run: |
          yarn
          yarn build
