name: CI
run-name: ${{ github.actor }} created a pull request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.4.0"
          cache: pnpm

      - uses: pnpm/action-setup@v2
        with:
          version: 8.7.0

      - name: Build project
        run: |
          pnpm install --frozen-lockfile
          pnpm check
          pnpm build
