name: CI
run-name: ${{ github.actor }} created a pull request

on:
  pull_request:
    branches:
    - main
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v3

    - name: Set up NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: yarn

    - name: Build
      run: |
        npm install
        npx webpack
